# Generated by Django 3.2.9 on 2021-11-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_reviews', models.IntegerField()),
                ('team_members', models.IntegerField()),
                ('happy_client', models.IntegerField()),
                ('completed_projects', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('WebD', 'Web Development'), ('SoftD', 'Software Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
