# Generated by Django 3.2.9 on 2021-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211118_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='social_link',
        ),
        migrations.AddField(
            model_name='team',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='insta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linked_in_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('WebD', 'Web Development'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
