# Generated by Django 3.2.9 on 2021-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211118_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='testimonials/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('DgtlM', 'Digtial Marketing'), ('AppD', 'App Development'), ('WebD', 'Web Development'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
