# Generated by Django 3.2.9 on 2021-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_quote_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('WebD', 'Web Development')], max_length=50),
        ),
    ]
