# Generated by Django 3.2.9 on 2021-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211118_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_field', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('WebD', 'Web Development'), ('SoftD', 'Software Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
