# Generated by Django 3.2.9 on 2021-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='package_field',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('SoftD', 'Software Development'), ('WebD', 'Web Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
