# Generated by Django 3.2.9 on 2021-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211119_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(choices=[('WebD', 'Web Development'), ('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('AppD', 'App Development')], max_length=50),
        ),
    ]
