# Generated by Django 3.2.9 on 2021-11-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211119_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('AppD', 'App Development'), ('SoftD', 'Software Development'), ('DgtlM', 'Digtial Marketing'), ('WebD', 'Web Development')], max_length=50),
        ),
    ]
