# Generated by Django 3.2.9 on 2021-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_quote_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('WebD', 'Web Development'), ('SoftD', 'Software Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
