# Generated by Django 3.2.9 on 2021-11-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211119_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('WebD', 'Web Development')], max_length=50),
        ),
    ]
