# Generated by Django 3.2.9 on 2021-11-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('WebD', 'Web Development'), ('AppD', 'App Development')], max_length=50),
        ),
    ]
