# Generated by Django 3.2.9 on 2021-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_quote_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('WebD', 'Web Development'), ('DgtlM', 'Digtial Marketing'), ('AppD', 'App Development'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
