# Generated by Django 3.2.9 on 2021-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20211119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('SoftD', 'Software Development'), ('WebD', 'Web Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
