# Generated by Django 3.2.9 on 2021-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20211119_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('DgtlM', 'Digtial Marketing'), ('WebD', 'Web Development'), ('SoftD', 'Software Development'), ('AppD', 'App Development')], max_length=50),
        ),
    ]
