# Generated by Django 3.2.9 on 2021-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211119_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_field', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('document', models.FileField(blank=True, upload_to='package_file/')),
            ],
        ),
        migrations.DeleteModel(
            name='place_order',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('WebD', 'Web Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
