# Generated by Django 3.2.9 on 2021-11-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20211120_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('WebD', 'Web Development'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
