# Generated by Django 3.2.9 on 2021-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_quote_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('SoftD', 'Software Development'), ('AppD', 'App Development'), ('DgtlM', 'Digtial Marketing'), ('WebD', 'Web Development')], max_length=50),
        ),
    ]
