# Generated by Django 3.2.9 on 2021-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_quote_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('AppD', 'App Development'), ('SoftD', 'Software Development'), ('WebD', 'Web Development'), ('DgtlM', 'Digtial Marketing')], max_length=50),
        ),
    ]
