# Generated by Django 3.2.9 on 2021-11-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211120_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/blogs/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('WebD', 'Web Development'), ('AppD', 'App Development')], max_length=50),
        ),
    ]
