# Generated by Django 3.2.9 on 2021-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20211120_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development'), ('AppD', 'App Development'), ('WebD', 'Web Development')], max_length=50),
        ),
    ]
