# Generated by Django 3.2.9 on 2021-11-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20211120_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='blog_slug',
        ),
    ]
