# Generated by Django 3.2.9 on 2021-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_slug_blog_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='field',
            field=models.CharField(blank=True, choices=[('AppD', 'App Development'), ('WebD', 'Web Development'), ('DgtlM', 'Digtial Marketing'), ('SoftD', 'Software Development')], max_length=50),
        ),
    ]
